### ISSUE TITLE
[BUG] DWCjProgressBar setValue() method has no huge effect.

### ISSUE THREAD

**Issue by Oskan1** [DwcJava/engine#106]
when I use the setMaximum() of 90 and use the code below, my progressBar grows "almost" as fast as when my setMaximum() is 10. 

There difference between having a max of 90 or 10 should be actualy noticeable. However, there is only a very small difference, which I believe, it doesnt work as it suppose to be.

```java
public class DWCjControlProgressBarSample extends App {
 private AppPanel appPanel;
 private ProgressBar firstProgressBar; 
 private Button modifyButton;
 
 @Override
 public void run() throws DwcAppInitializeException {
 appPanel = new AppPanel();

 firstProgressBar = new ProgressBar();
 appPanel.add(firstProgressBar);

 firstProgressBar.setMaximum(90);

modifyButton.onClick(this::onClick);
}

private void onClick(ButtonClickEvent buttonClickEvent){
     value();
}

private void value(){
       boolean flag = false;
       while (!flag){
           firstProgressBar.setValue(firstProgressBar.getValue() + 1);
           if(Objects.equals(firstProgressBar.getValue(), firstProgressBar.getMaximum())){
               flag = true;
           }
      }
}
```

**Comment by mhawkinsbasis** [comment]
To me, I believe it's a noticeable enough effect, and may be useful to those who are used to using this method in existing DWC applications

**Comment by hyyan** [comment]
> when I use the setMaximum() of 90 and use the code below, my progressBar grows "almost" as fast as when my setMaximum() is 10.

I cannot reproduce such behavior Oskan. Make sure  you are using the latest version of BBj
