### ISSUE TITLE
Create a "display filtered results" functionality for the TextComboBox

### ISSUE THREAD

**Issue by mhawkinsbasis** [DwcJava/engine#127]

**Comment by hyyan** [comment]
@mhawkinsbasis What is that ?

**Comment by mhawkinsbasis** [comment]
Functionality to open the options in the list and then filter them based on what is being entered in the text field of the control (the functionality we were asked about yesterday by Prodin)

**Comment by hyyan** [comment]
I think we don't want this in here. Write a sample and share it with them. This is not how auto-complete should work
