### ISSUE TITLE
errors reported for pom.xml

### ISSUE THREAD

**Issue by StephanWald** [DwcJava/engine#167]
The following two lines are reported by the IDE as error:

https://github.com/DwcJava/engine/blob/7b819ebd3002d575b4e2db072a941c2c4f097bdd/pom.xml#L207

https://github.com/DwcJava/engine/blob/7b819ebd3002d575b4e2db072a941c2c4f097bdd/pom.xml#L253

How can these error reports be avoided, or do these lines need fixing?

**Comment by khmarbaise** [comment]
In which way does the IDE report errors for those lines?

**Comment by StephanWald** [comment]
![image](https://user-images.githubusercontent.com/4833070/214832052-3a804415-80f2-45e5-b0e0-054ce5ca56ba.png)

![image](https://user-images.githubusercontent.com/4833070/214832149-72a0f86c-e092-42ee-b605-4bd18e4bbbd1.png)

**Comment by khmarbaise** [comment]
The first one `${arguments}` is shown because IDEA assumes every property must be defined under all circumstances which is not always the case. The second one means the IDEA integration is not aware of that configuration.
