### ISSUE TITLE
[BUG] select() from DWCjTextBox Control is not working both in DWCj and DWC(it works in GUI and BUI)

### ISSUE THREAD

**Issue by Oskan1** [DwcJava/engine#174]
DWCj Code below:
```java
import org.dwcj.App;
import org.dwcj.controls.panels.AppPanel;
import org.dwcj.controls.textbox.TextBox;
import org.dwcj.exceptions.DwcAppInitializeException;

public class GetSelectedTextTextBox extends App {

    @Override
    public void run() throws DwcAppInitializeException {
        AppPanel appPanel = new AppPanel();

        TextBox textBox = new TextBox("HHIHIHII");
        appPanel.add(textBox);

        textBox.select(2,5);
    }
}
```

BUI, GUI BBj Code below:
sysgui = unt
open (sysgui)"X0"
sysgui! = bbjapi().getSysGui()
window! = sysgui!.addWindow(100,100,350,125,"select",$00090083$)
window!.setCallback(window!.ON_CLOSE,"eoj")

text$ = "The quick brown fox jumps over the lazy dog."

editbox! = window!.addEditBox(101,25,25,300,25,text$,$$)
editbox!.focus()
select! = window!.addToolButton(102,25,75,150,25,"Select",$$)
select!.setCallback(select!.ON_TOOL_BUTTON_PUSH,"select")

process_events

eoj:
release

select:
editbox!.select(4,9)
return

**Comment by hyyan** [comment]
See https://github.com/DwcJava/engine/issues/132
