### ISSUE TITLE
[BUG] setPasswordVisible() for TextBox() doesnt work. (in bbj works)

### ISSUE THREAD

**Issue by Oskan1** [DwcJava/engine#215]
DWCj Code sample:
```javac
import org.dwcj.App;
import org.dwcj.controls.panels.AppPanel;
import org.dwcj.controls.textbox.TextBox;
import org.dwcj.exceptions.DwcException;

public class PasswordVisible extends App {

    @Override
    public void run() throws DwcException {
        AppPanel appPanel = new AppPanel();
        
        TextBox myBox = new TextBox();
        appPanel.add(myBox);
        
        myBox.setPasswordVisible(false);
    }
}
```

BBj Code sample:
sysgui = unt
open (sysgui)"X0"
sysgui! = bbjapi().getSysGui()
window! = sysgui!.addWindow(100,100,300,150,"setPasswordVisible",$00090003$)
window!.setCallback(window!.ON_CLOSE,"eoj")
window!.addStaticText(101,5,30,65,25,"Password:",$8000$)
password! = window!.addEditBox(102,75,25,200,25,"xyzzy",$0400$)
visible! = window!.addCheckBox(103,75,75,200,25,"setPasswordVisible",$$)
visible!.setCallback(visible!.ON_CHECK_ON,"visible")
visible!.setCallback(visible!.ON_CHECK_OFF,"invisible")
process_events
eoj:
release
visible:
password!.setPasswordVisible(1)
print "isPasswordVisible? ",password!.isPasswordVisible()
return
invisible:
password!.setPasswordVisible(0)
print "isPasswordVisible? ",password!.isPasswordVisible()
return

**Comment by Oskan1** [comment]
This issue occurs because the "type" attribute needs to be set to "password".
ENUM Implementation for different type values is needed.

**Comment by hyyan** [comment]
method removed
