### ISSUE TITLE
Importing a non-supported Icon

### ISSUE THREAD

**Issue by mhawkinsbasis** [DwcJava/engine#434]
From Prodin:

"When you use an icon that is not available (I picked some icons from https://tabler-icons.io/, but I don’t think all are available in DWCJ), the whole app crashes. Maybe good idea to fall back on a default icon or show a “broken” icon like you see sometimes when images can not be loaded? Just a thought."

**Comment by hyyan** [comment]
Should be possible with BBj nightly build. This is not DWCj related.
