### ISSUE TITLE
[BUG] RadioButton/Switch Label does not properly align

### ISSUE THREAD

**Issue by MatthewHawkins** [DwcJava/engine#455]
**Describe the bug**
When I create a radio button or switch component on the screen that takes up more vertical space than the component's own size, the label does not stay aligned with the component.

**To Reproduce**
1. Create a RadioButton/Switch
2. Ensure the component takes up more vertical space than it needs to display the component itself

**Expected behavior**
Regardless of available space, component's label should be aligned with the component

**Screenshots**
![image](https://github.com/DwcJava/engine/assets/56275404/a6b30e2a-d37c-453e-ac86-978edc9f9220)

**Software Versions (please complete the following information)**
 - Java Version: openjdk 17.0.4.1 **2022-08-12**
 - DWCJ version: [e.g 23.06-SNAPSHOT]
 - BBj Version: [e.g 23.10(Beta)]

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [119.0.6045.159]

**Comment by hyyan** [comment]
@MatthewHawkins Test again please with nightly build and let me know if it is fixed for you or paste a runnable code that I can use to reproduce

**Comment by MatthewHawkins** [comment]
Tested with 23.06 BBj and the issue is resolved.
