### ISSUE TITLE
`HtmlContainerJavascriptEvent` eventMap should be of type `Map<String,String>`

### ISSUE THREAD

**Issue by hyyan** [DwcJava/engine#78]
Change the eventMap type from `Map<Object,Object>` to `Map<String,String>` for completability with BBj API

**Comment by StephanWald** [comment]
That's not entirely correct. The event map can be nested, so a key can contain another nested map with more contents. Didn't find a proper solution for that as yet, we may consider a true event map class at a later stage.

**Comment by hyyan** [comment]
The event Map is defined in BBj as `HashMap<String,String>`. The map cannot contain nested data. The value is always a string. If the event's detail coming from the client is nested then it is transformed intro JSON before it is sent to the server.
