### ISSUE TITLE
Adding the same panel with its controls twice to a AppPanel fails. 

### ISSUE THREAD

**Issue by hyyan** [DwcJava/engine#95]
The following code does not work. It seem the route of this problem is the `catchUp` method which prevents invoking itself twice.

```java
AppPanel panel = new AppPanel();

Div c = new Div();
c.addClassName("my-class");
c.add(new Label("My Text"));

panel.add(c);
panel.add(c);
```

**Comment by StephanWald** [comment]
What should happen when you add the same (identical) control object twice? Each DWC control instance is linked to a BBj control instance, so adding the same instance twice makes no sense.

The "add" should probably throw an exception that a control cannot be added twice, or what do you foresee that happens?

**Comment by hyyan** [comment]
You are right. The `add` should throw an exception in this case.

1. So we should, auto generate a unique id every time an instance of control is created. 
2. Override `hashCode` method in each control to return that unique id
3. When a control is added to a panel we compare the hashCode and throw an exception 

I think the unique id will be helpful also to look up a control in the panel. `Control getControl(String id)`

**Comment by StephanWald** [comment]
should that ID that you envision then be also the ID in the DOM?

**Comment by hyyan** [comment]
> should that ID that you envision then be also the ID in the DOM?

No. The unique id is meaningful only in the server. and We don't wanna slow things down by asking the client for the nodes ids plus the DOM id is not available before a control is is attached to a panel.

**Comment by hyyan** [comment]
What should happens when the same control instance is added twice in two separated panels ?

**Comment by hyyan** [comment]
Resolved through https://github.com/DwcJava/engine/pull/466
